SELECT  EMP_ID, EMP_NAME,EMP_NO, EMAIL, PHONE,
	NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAMe, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;


-- why NATRUL JOIN 안되는거지?  ( 순서 중요! )
SELECT  EMP_ID, EMP_NAME,EMP_NO, EMAIL, PHONE,
	NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
NATURAL JOIN JOB 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);
ORDER BY EMP_ID;


INSERT INTO EMPLOYEE VALUES('300','유은서','0123','vegayes@naver.com','01012345','D2','J5','S5','200000',
'0.1','200','2020-01-01','2023-01-01','Y');


SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE
WHERE EMP_NAME  ='유은서';

COMMIT;
ROLLBACK;



SELECT  EMP_ID, EMP_NAME,EMP_NO, EMAIL, PHONE,
	NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE EMP_NO = '861015-1356452' 
ORDER BY EMP_ID;


SELECT NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, SUM(SALARY) SUM_SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
GROUP BY DEPT_TITLE 
ORDER BY SUM_SALARY DESC;


SELECT JOB_NAME, ROUND(AVG(SALARY),1) AVG_SALARY
FROM EMPLOYEE
NATURAL JOIN JOB 
GROUP BY JOB_NAME 
ORDER BY AVG_SALARY DESC;






